substitutions:
  _PROJECT_ID: finalproject-478423
steps:
  # Build the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/recipe-backend', './backend']

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_PROJECT_ID}/recipe-backend']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'recipe-backend',
        '--image', 'gcr.io/${_PROJECT_ID}/recipe-backend',
        '--platform', 'managed',
        '--region', 'us-central1',
        '--allow-unauthenticated',
        '--port','8080',
        '--set-env-vars', 'MONGODB_URI=mongodb+srv://nellysoans8_db_user:d2kXsY2WEtzeElJd@cluster0.0c0lwv7.mongodb.net/soccer-teams-mapper',
      ]

# Add logging configuration
options:
  logging: CLOUD_LOGGING_ONLY